### ISSUE TITLE
Where exactly does the "Microsoft TrueType Fonts" license come from?

### ISSUE THREAD

**Issue by ArrayBolt3** [mrbvrz/Segoe-UI-Font-Ubuntu#13]
I'm concerned about actually trying to use this font, although it does look very convenient and would be useful for me.

It appears however that the license in this project may have been copied from Microsoft's Core Fonts for the Web project and applied to Segoe UI. I'm not sure if that's actually correct, as Microsoft's [font redistribution FAQ](https://learn.microsoft.com/en-us/typography/fonts/font-faq) states:

> ...as Segoe UI is both our user interface and corporate branding font, it is not available for use outside of Microsoft products on non-Windows platforms.

Where does the license in this repository come from? Is it certain that it actually applies to Segoe UI?

**Comment by mrbvrz** [comment]
Segoe font details can be seen here https://learn.microsoft.com/en-us/typography/font-list/segoe-ui

This repository only makes it easier for you to install Segoe fonts on your Linux, and I know this font is not open source. The use of this font really hopes for your discretion.

Thank You.
