### ISSUE TITLE
Wont install segoe ui. 

### ISSUE THREAD

**Issue by DrVektor** [mrbvrz/Segoe-UI-Font-Ubuntu#15]
>  
                                         _    __            _   
                                        (_)  / _|          | |  
  ___  ___  __ _  ___   ___        _   _ _  | |_ ___  _ __ | |_ 
 / __|/ _ \/ _  |/ _ \ / _ \  __  | | | | | |  _/ _ \|  _ \| __|
 \__ \  __/ (_| | (_) |  __/ (__) | |_| | | | || (_) | | | | |_ 
 |___/\___|\__, |\___/ \___|       \__,_|_| |_| \___/|_| |_|\__|
            __/ |                                               
           |___/              mrbvrz - https://hasansuryaman.com        

 ---------------------------------------------------------------

 [ * ] Checking for internet connection
 [ X ] Internet Connection ➜ OFFLINE!

 Sorry, you really need an internet connection....
[dogon@archlinux segoe-ui-linux]$ 
this is the output of when run the install.sh. I didnt understand how to ass wine-prefix?

**Comment by mrbvrz** [comment]
change `nc` to `curl` c745e2007aff0444b1d20ccd1c468dee115d0228
