### ISSUE TITLE
Installer suggestion does not work.

### ISSUE THREAD

**Issue by xa2099** [mrbvrz/Segoe-UI-Font-Ubuntu#16]
Thank you for the font! 
Much appreciated! :)

https://github.com/mrbvrz/segoe-ui-linux/blob/73b3a40c6c433d3b8149d945d4c441d4497d5f79/README.md?plain=1#L18C1-L20C13

Did not work...

![image](https://github.com/mrbvrz/segoe-ui-linux/assets/37461099/93de270c-3968-49dc-a499-94253129ff4b)

```
git clone https://github.com/SpudGunMan/segoe-ui-linux
sudo bash ./segoe-ui-linux/bash install.sh
```

**Comment by mrbvrz** [comment]
updated on c745e2007aff0444b1d20ccd1c468dee115d0228
