### ISSUE TITLE
Cannot find internet connection even though device is online

### ISSUE THREAD

**Issue by Respnsbl6** [mrbvrz/Segoe-UI-Font-Ubuntu#19]
For some reason, install.sh says that I need an internet connection, however I am connected.

I am running Ubuntu 22.04.4 LTS with a wired connection, can anybody help me out?

**Comment by darkmmode** [comment]
just remove this section in the script, as thats how i fixed it 
![image](https://github.com/mrbvrz/segoe-ui-linux/assets/132021656/0a7ab780-71b6-45b8-8d11-9842b05e1be0)
