### ISSUE TITLE
Installer doesn't check if downloaded font files aren't empty

### ISSUE THREAD

**Issue by intarstudents** [mrbvrz/Segoe-UI-Font-Ubuntu#2]
I don't know how I managed it, but for me installer installed font files like this:
 
![20200316af2301](https://user-images.githubusercontent.com/227198/76758850-3711fa80-6793-11ea-922d-f874b007f42e.png)

And that made using web with this font italic'ly weird :)

**Comment by mrbvrz** [comment]
i still looking for this solution, so far i think the way just delete file and reinstall.
