### ISSUE TITLE
Does this include Segoe UI Emoji?

### ISSUE THREAD

**Issue by Botspot** [mrbvrz/Segoe-UI-Font-Ubuntu#4]
If you install these fonts, will full-color emojis be displayed in web browsers?

**Comment by mrbvrz** [comment]
@Botspot for now it only consists of the segoe-ui family font, does not include the segoe-ui emoji font family, segoe script or segoe print

**Comment by Botspot** [comment]
Would you be able to add that?

**Comment by SpudGunMan** [comment]
forked with https://github.com/SpudGunMan/segoe-ui-linux

**Comment by mrbvrz** [comment]
I have merged at 57c4e38379f49898ef291d1b8bc9d4f8f5c72825
thanks [SpudGunMan](https://github.com/SpudGunMan)

**Comment by Botspot** [comment]
There are multiple syntax errors on @SpudGunMan's PR.

**Comment by SpudGunMan** [comment]
Was surprised it was fully consumed. My fork is primary use case was for wine so. I will be leaving my fork and agree.
