### ISSUE TITLE
Internet connexion check says i'm offline

### ISSUE THREAD

**Issue by ghost** [mrbvrz/Segoe-UI-Font-Ubuntu#6]
Internet connexion check says i'm offline

**Comment by KunalAwasthi** [comment]
- Just simply copy install.sh content.
- run `nano install.sh` in your terminal.
- Paste content copied from install.sh and comment `cekkoneksi` in `main` function.

I guess `echo -e "GET http://google.com HTTP/1.0\n\n" | nc google.com 80` is not working fine.

**Comment by ghost** [comment]
Thanks
