### ISSUE TITLE
Why this message in the Readme?

### ISSUE THREAD

**Issue by frederikhors** [mrbvrz/Segoe-UI-Font-Ubuntu#8]
@mrbvrz why after the yesterday release there is this message in the Readme?

`Forked and updated by SpudGunMan`

**Comment by frederikhors** [comment]
I forgot: thank you for this great work!

**Comment by mrbvrz** [comment]
this a PR from [SpudGunMan/segoe-ui-linux](https://github.com/SpudGunMan/segoe-ui-linux) repo.
